# Skriv detta i terminalen:
# docker-compose up -d 
version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - group-project-network

  todoservice:
    image: todo
    container_name: container_todo
    environment:
      - PORT=4000
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - MONGO_DB=todosdb
      - TODOS_API_KEY=8fcbdb72c9d74a36be7413388341a6c0d547dd2ade2a4ee2aa13e9b16c12a63b
      - USER_SERVICE_URL=http://userservice:4001
    ports:
      - "4000:4000"
    networks:
      - group-project-network

  userservice:
    image: user
    container_name: container_user
    environment:
      - PORT=4001
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - MONGO_DB=userdb
      - TODOS_API_KEY=8fcbdb72c9d74a36be7413388341a6c0d547dd2ade2a4ee2aa13e9b16c12a63b
      - TOKEN_SECRET_KEY=f04(/&(&/(0ab1e-c2f0=)(€/(#4c4e-889e-541kdshdsnv87234b8/hd+???=(!--.4eb9e5017
    ports:
      - "4001:4001"
    networks:
      - group-project-network
  
  frontend:
    image: frontend
    container_name: container_frontend
    environment:
      - PORT=80
    ports:
      - "80:80"
    networks:
      - group-project-network

networks:
  group-project-network:
    driver: bridge